import { Kumbh_Sans, Mulish } from "next/font/google";
import "./globals.css";
import { Header } from "./partials/layout/header";
import { Footer } from "./partials/layout/footer";

const kumbhSans = Kumbh_Sans({
  variable: "--font-kumbh-sans",
  subsets: ["latin"],
});
const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata = {
  title: "Invest Theme",
  description: "Generated by invest",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${kumbhSans.variable} ${mulish.variable} antialiased flex min-h-screen flex-col`}
      >
        <Header />
        <main className="flex-1">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
